### ISSUE TITLE
Create a Biolatency plugin

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/lokomotive-web-ui#23]
We want to create a plugin for easily exposing the biolatency new gadget of Inspektor Gadget.

This gadget acts on custom resources and runs per node. The custom resource definition/spec will be posted here soon.
For this plugin we want to have a new section on each node details view, so we need [new functionality from the plugin lib](https://github.com/kinvolk/headlamp/issues/310).

The plugin has 3 modes: idle (no latency data yet), running (calculating the latency), and results (a chart showing the results).

**Update:** Any user-visible text about biolatency should rather be "Block I/O Latency" (i.e. the section's title should not be the one in the mockups)

## Idle/begin:

![ig_biolatency](https://user-images.githubusercontent.com/1029635/130224190-683db7f5-504b-4a47-af28-8ea543912f78.png)

## Running

![ig_biolatency_running](https://user-images.githubusercontent.com/1029635/130224275-bc1e60dd-d0b2-4993-87c7-4d18d9aca76f.png)

## Results

![ig_biolatency_finished](https://user-images.githubusercontent.com/1029635/130224299-c2f75b87-4a88-4e61-80b5-b09c2447bc90.png)

**Comment by alban** [comment]
Some links how to do this:

* [trace-biolatency.yaml](https://github.com/kinvolk/inspektor-gadget/blob/main/pkg/resources/samples/trace-biolatency.yaml): example of Trace resource to create for the biolatency gadget
* [Example of Go code](https://github.com/kinvolk/inspektor-gadget/blob/f0aea300d2291f6c7c321c4aa35f66ed85490521/cmd/kubectl-gadget/collector.go#L204-L239) creating a Trace resource. In this example, the name of the resource is not chosen by the client but by the API server by using the `GenerateName` field.
* [Description of the Trace CRD](https://github.com/kinvolk/inspektor-gadget/blob/main/pkg/resources/crd/bases/gadget.kinvolk.io_traces.yaml)
